services:
  websites:
    image: nginx:latest
    container_name: reports_qa_automation
    volumes: 
      - ./target/surfire-reports/testng-native-results:/usr/share/nginx/html
    ports:
      - "8081:80"
    restart: always